server:
  port: 8080

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  ##数据源
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.105:3306/web_db?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456

  jpa:
    ##指定数据库
    database: mysql
    ##是否显示执行sql语句
    show-sql: true
    hibernate:
      ##自动更新数据库表,若需要创建表则改为create
      ddl-auto: update
      naming:
        ##字段映射规则
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl



  ##模板
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html


